### ISSUE TITLE
remove glmer as shortcut to lmer

### ISSUE THREAD

**Issue by nickreich** [Kenkleinman/clusterPower#12]
Warning in glmer(y ~ trt + (1 | clust), data = dat, family = outcome.type,  :
  calling glmer() with family=gaussian (identity link) as a shortcut to lmer() is deprecated; please call lmer() directly

Need an update to remove a letter from a function?

**Comment by Kenkleinman** [comment]
Sorry, I didn't realize that was opaque-- I forgot you don't always use random effects.

This is the example from help(power.sim.normal), except swapping random.effect for fixed.effect in estimation.function:

> a <- power.sim.normal(n.sim=10, effect.size=5, alpha=.05, n.clusters=2, n.periods=2, 
                      cluster.size=20, btw.clust.var=5, ICC=1/20, period.effect=2, 
                      estimation.function=random.effect, verbose=TRUE, period.var=0)
starting simulation :: 2016-01-05 16:01:31
iteration 10 :: 2016-01-05 16:01:31
power = NA
There were 20 warnings (use warnings() to see them)

> warnings()
...
19: In glmer(y ~ trt + (1 | clust), data = dat, family = outcome.type,  ... :
  calling glmer() with family=gaussian (identity link) as a shortcut to lmer() is deprecated; please call lmer() directly
