### ISSUE TITLE
cps.normal: !is.integer() does not function properly during user input validation

### ISSUE THREAD

**Issue by arbogdan** [Kenkleinman/clusterPower#17]
When running the code using `!is.integer()` to ensure nsim, n, m, and difference are all whole numbers, function will properly run for first function call, but any subsequent calls of `cps.normal` will classify nsim, n, m, and difference as class: double and will result in error message. While not an issue in and of itself, after this point neither `!is.integer()` OR 'is.integer()` work; both come back FALSE.

I suspect this may be an issue specific to my machine.

The helper function `is.wholenumber` is created to address this issue, however using `is.integer()` would be preferred.

**Comment by acbro0** [comment]
this is fixed
