### ISSUE TITLE
functions that probably don't need to be exported

### ISSUE THREAD

**Issue by Kenkleinman** [Kenkleinman/clusterPower#202]
argmatch
bincalcicc
confintcalc
*.*.*.internal
createmissingvarianceparam
expit
logit
is.wholenumber
make.base.data
mixed.eff.params
optimizersearch
package.R ?
print.crtpwr
prop_H0_rejection
random.effect
runExample
summary-method
type1errortest
validatevariance
weighted.crossover.cluster.level

These appear in the "Help Pages" for the package, but the user probably doesn't need to know they exist.  I assume they are there because exported?

**Comment by acbro0** [comment]
removed @export tags, now must add #' @keywords internal tag to prevent documentation

**Comment by acbro0** [comment]
this is done. The only exception is binCalcICC, which is not an internal function.
