### ISSUE TITLE
Documentation issue: Question on sigma_b_sq (fast question)

### ISSUE THREAD

**Issue by jamesdalg** [Kenkleinman/clusterPower#217]
What is the meaning of sigma_b_sq in cps.ma.binary? Is it interpreted to mean the variance in the binary outcome or is it interpreted to mean the variance in the size of the clusters?

**Comment by Kenkleinman** [comment]
It's the variance of the random effects in the data generating model.  This is shown in cps.binary, but hasn't yet filtered down into cps.ma.binary yet.  It'll get there eventually.  Thanks for this reminder!

**Comment by nandanrao** [comment]
A related note on the same part of the documentation (happy to open a new issue if you prefer, just let me know): 

The "data generating model", as documented in the cps.binary function, I believe is missing an important point: it's not `p1` but rather the `logit(p1)` that is added to the noise and then put into a sigmoid function to determine the probability of the y_ij. 

Unless I'm misreading the code and/or misunderstanding the model?

In any case, the documentation is great, thanks for all of this! But clarifying that small thing might help some people in the future :)

**Comment by Kenkleinman** [comment]
Hi Nandan--  I think the documentation is right, but can you open an issue and cut-and-paste the section where you think it's in error?
