### ISSUE TITLE
consider IRGTT vs. generic two-arm trial syntax

### ISSUE THREAD

**Issue by Kenkleinman** [Kenkleinman/clusterPower#33]
in cps.normal line 250-285 vs. 290- 335;  IRGTT uses 0. as.factor, other does not.  Is there an effect of this?????

**Comment by Kenkleinman** [comment]
The idea was that 0+ syntax would make the two types of RE be uncorrelated, but is this true???

**Comment by acbro0** [comment]
new line numbers: 571, 504
L571 & 584: want 0+as.factor
603 & 608: want 0+as.factor
637 & 649: don't change
666: don't change

**Comment by acbro0** [comment]
run a simulation with 100 with code that works and generates non-trivial power, then change code to as discussed above and run again and tell Ken what the two answers are.

**Comment by acbro0** [comment]
The results are identical.

**Comment by acbro0** [comment]
Sorry, I didn't mean to close this issue. I'm sending you an update soon.

**Comment by Kenkleinman** [comment]
The notion here is that we are modeling random effects for each treatment group.  These random effects should not, in theory, be correlated-- why should they be?  The two codes in question are 

lmer(y ~ trt + (0 + as.factor(trt) | clust)

and

lmer(y ~ trt + (1 + as.factor(trt) | clust)

The thinking is that the former code, by specifying that there is no random intercept, makes there be a random effect for each level of trt.  The second code, by allowing a random intercept for each unit and a random effect for one level of the trt variable, results in correlated random effects.

**Comment by Kenkleinman** [comment]
We went with the 0+trt formulation.
