### ISSUE TITLE
update nlme function call with better optimizer

### ISSUE THREAD

**Issue by joshua-nugent** [Kenkleinman/clusterPower#40]
In cps.ma.internal...

I had told ken and lexi earlier that the code for the 'varying sigma2_b and varying sigma' should be this, and it was implemented:
`      my.mod <- nlme::lme(y~as.factor(trt2), random=~1+as.factor(trt2)|clust2, 
                     weights=nlme::varIdent(form=~1|as.factor(trt2)), 
                     method="ML",
                     control=nlme::lmeControl(opt='optim'))
`
BUT to converge more consistently, set the optimizer to Nelder-Mead. Should look something like:
  `    my.mod <- nlme::lme(y~as.factor(trt2), random=~1+as.factor(trt2)|clust2, 
                     weights=nlme::varIdent(form=~1|as.factor(trt2)), 
                     method="ML",
                   control = lmeControl(opt = "optim", optimMethod = "Nelder-Mead"))`

**Comment by Kenkleinman** [comment]
User can now set the optimizer.  This is likely best.
