### ISSUE TITLE
line widths in documentation files

### ISSUE THREAD

**Issue by nickreich** [Kenkleinman/clusterPower#9]
- checking Rd line widths ... NOTE
  Rd file ‘hayes.power.poisson.Rd’:
  \usage lines wider than 90 characters:
     hayes.power.poisson(n.clusters, period.effect, btw.clust.var, at.risk.params, cluster.size, effect.size, alpha=.05)
  \examples lines wider than 100 characters:
     hayes.power.poisson(n.clusters=36, period.effect=log(.015), btw.clust.var=0, at.risk.params=20, cluster.size=20, effect.size=log(.7))

These lines will be truncated in the PDF manual.

Please fix, and re-check with R-patched or R-devel.

**Comment by YinLiLin** [comment]
I attempt to upload a package to R, but after chenking, there is a problem which is the same with your writing, I don't know how to sovle the problem, I wonder whether you have solved, can you tell me your method to solve this problem? thanks a lot!
